version: '3'

services:
  ### Auth Service
  mongodb_auth_service:
    container_name: mongodb_auth_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=authService
      - MONGO_INITDB_ROOT_PASSWORD=authService
    ports:
      - "27017"
    volumes:
      - mongodb-authService-data:/data/db

  mongo-express-auth:
    container_name: mongo-express-auth
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://authService:authService@mongodb_auth_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=authService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=authService
    depends_on:
      - mongodb_auth_service
    ports:
      - "8081:8081"

  auth-service:
    container_name: auth-service
    build: ./rewarding-sale-app-auth-service
    depends_on:
      - mongodb_auth_service
    deploy:
      mode: replicated
      replicas: 1

  ### Post Service
  mongodb_post_service:
    container_name: mongodb_post_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=postService
      - MONGO_INITDB_ROOT_PASSWORD=postService
    ports:
      - "27017"
    volumes:
      - mongodb-postService-data:/data/db

  mongo-express-post:
    container_name: mongo-express-post
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://postService:postService@mongodb_post_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=postService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=postService
    depends_on:
      - mongodb_post_service
    ports:
      - "8082:8081"

  post-service:
    container_name: post-service
    build: ./rewarding-sale-app-post-service
    depends_on:
      - mongodb_post_service
    deploy:
      mode: replicated
      replicas: 1


  ### Admin Service
  mongodb_admin_service:
    container_name: mongodb_admin_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adminService
      - MONGO_INITDB_ROOT_PASSWORD=adminService
    ports:
      - "27017"
    volumes:
      - mongodb-adminService-data:/data/db

  mongo-express-admin:
    container_name: mongo-express-admin
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://adminService:adminService@mongodb_admin_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=adminService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=adminService
    depends_on:
      - mongodb_admin_service
    ports:
      - "8083:8081"

  admin-service:
    container_name: admin-service
    build: ./rewarding-sale-app-admin-service
    depends_on:
      - mongodb_admin_service
    deploy:
      mode: replicated
      replicas: 1


  ### Search Service
  mongodb_search_service:
    container_name: mongodb_search_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=searchService
      - MONGO_INITDB_ROOT_PASSWORD=searchService
    ports:
      - "27017"
    volumes:
      - mongodb-searchService-data:/data/db

  mongo-express-search:
    container_name: mongo-express-search
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://searchService:searchService@mongodb_search_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=searchService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=searchService
    depends_on:
      - mongodb_search_service
    ports:
      - "8084:8081"

  search-service:
    container_name: search-service
    build: ./rewarding-sale-app-search-service
    depends_on:
      - mongodb_search_service
    deploy:
      mode: replicated
      replicas: 1

  ##Comment Service
  mongodb_comment_service:
    container_name: mongodb_comment_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=commentService
      - MONGO_INITDB_ROOT_PASSWORD=commentService
    ports:
      - "27017"
    volumes:
      - mongodb-commentService-data:/data/db

  mongo-express-comment:
    container_name: mongo-express-comment
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://commentService:commentService@mongodb_comment_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=commentService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=commentService
    depends_on:
      - mongodb_comment_service
    ports:
      - "8085:8081"

  comment-service:
    container_name: comment-service
    build: ./rewarding-sale-app-comment-service
    depends_on:
      - mongodb_comment_service
    deploy:
      mode: replicated
      replicas: 1

  ##Vote Service

  mongodb_vote_service:
    container_name: mongodb_vote_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=voteService
      - MONGO_INITDB_ROOT_PASSWORD=voteService
    ports:
      - "27017"
    volumes:
      - mongodb-voteService-data:/data/db

  mongo-express-vote:
    container_name: mongo-express-vote
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://voteService:voteService@mongodb_vote_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=voteService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=voteService
    depends_on:
      - mongodb_vote_service
    ports:
      - "8086:8081"

  vote-service:
    container_name: vote-service
    build: ./rewarding-sale-app-vote-service
    depends_on:
      - mongodb_vote_service
    deploy:
      mode: replicated
      replicas: 1

  ##Rewards
  mongodb_reward_service:
    container_name: mongodb_reward_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rewardService
      - MONGO_INITDB_ROOT_PASSWORD=rewardService
    ports:
      - "27017"
    volumes:
      - mongodb-rewardService-data:/data/db

  mongo-express-reward:
    container_name: mongo-express-reward
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://rewardService:rewardService@mongodb_reward_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=rewardService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=rewardService
    depends_on:
      - mongodb_reward_service
    ports:
      - "8087:8081"

  reward-service:
    container_name: reward-service
    build: ./rewarding-sale-app-rewards-service
    depends_on:
      - mongodb_reward_service
    deploy:
      mode: replicated
      replicas: 1

  ##Report
  mongodb_report_service:
    container_name: mongodb_report_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=reportService
      - MONGO_INITDB_ROOT_PASSWORD=reportService
    ports:
      - "27017"
    volumes:
      - mongodb-reportService-data:/data/db

  mongo-express-report:
    container_name: mongo-express-report
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://reportService:reportService@mongodb_report_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=reportService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=reportService
    depends_on:
      - mongodb_report_service
    ports:
      - "8088:8081"

  report-service:
    container_name: report-service
    build: ./rewarding-sale-app-report-service
    depends_on:
      - mongodb_report_service
    deploy:
      mode: replicated
      replicas: 1

  ##Decision Service
  mongodb_decision_service:
    container_name: mongodb_decision_service
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=decisionService
      - MONGO_INITDB_ROOT_PASSWORD=decisionService
    ports:
      - "27017"
    volumes:
      - mongodb-decisionService-data:/data/db

  mongo-express-decision:
    container_name: mongo-express-decision
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://decisionService:decisionService@mongodb_decision_service:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin  #mongo-express web username
      - ME_CONFIG_BASICAUTH_PASSWORD=admin  #mongo-express web password
      - ME_CONFIG_MONGODB_AUTH_USERNAME=decisionService
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=decisionService
    depends_on:
      - mongodb_decision_service
    ports:
      - "8089:8081"

  decision-service:
    container_name: decision-service
    build: ./rewarding-sale-app-decision-service
    depends_on:
      - mongodb_decision_service
    deploy:
      mode: replicated
      replicas: 1


  ### Reverse Proxy - Nginx
  nginx:
    container_name: nginx
    build: ./rewarding-sale-app-nginx-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - post-service
      - admin-service
      - search-service
      - comment-service
      - vote-service
      - reward-service
      - report-service
      - decision-service

volumes:
  mongodb-authService-data:
    driver: local

  mongodb-postService-data:
    driver: local

  mongodb-adminService-data:
    driver: local

  mongodb-searchService-data:
    driver: local

  mongodb-commentService-data:
    driver: local

  mongodb-voteService-data:
    driver: local

  mongodb-rewardService-data:
    driver: local

  mongodb-reportService-data:
    driver: local

  mongodb-decisionService-data:
    driver: local